# Generated by Django 4.2 on 2023-04-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Yo`nalish',
                'verbose_name_plural': 'Yo`nalishlar',
            },
        ),
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=150, verbose_name='Familiyasi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('birthday', models.DateField(verbose_name='Tug`ilgan sanasi')),
                ('age', models.PositiveIntegerField(verbose_name='Yoshi')),
                ('gender', models.CharField(choices=[('Male', 'Erkak'), ('Female', 'Ayol')], max_length=15, verbose_name='Jinsi')),
                ('image', models.ImageField(default='internship/intern/image/default-user.png', upload_to='internship/intern/image/', verbose_name='Rasmi')),
                ('resume_file', models.FileField(upload_to='internship/intern/resume_file/', verbose_name='CV')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interns', to='internship.direction', verbose_name='Yo`nalishi')),
            ],
            options={
                'verbose_name': 'Amaliyotchi',
                'verbose_name_plural': 'Amaliyotchilar',
            },
        ),
    ]
