# Generated by Django 4.2 on 2023-04-13 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('home_address', models.CharField(max_length=250, verbose_name='Uy manzili')),
            ],
            options={
                'verbose_name': 'Manzil',
                'verbose_name_plural': 'Manzillar',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slugi')),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slugi')),
            ],
            options={
                'verbose_name': 'Viloyat/Shahar',
                'verbose_name_plural': 'Viloyat/Shaharlar',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('first_name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=150, verbose_name='Familiyasi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('birthday', models.DateField(verbose_name='Tug`ilgan sanasi')),
                ('age', models.PositiveIntegerField(verbose_name='Yoshi')),
                ('gender', models.CharField(choices=[('Male', 'Erkak'), ('Female', 'Ayol')], max_length=15, verbose_name='Jinsi')),
                ('image', models.ImageField(default='employees/employee/image/default-user.png', upload_to='employees/employee/image/', verbose_name='Rasmi')),
                ('resume_file', models.FileField(upload_to='employees/employee/resume_file/', verbose_name='CV')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maoshi')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.address')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.position', verbose_name='Lavozimi')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slugi')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='employees.region', verbose_name='Viloyati')),
            ],
            options={
                'verbose_name': 'Tuman/Shahar',
                'verbose_name_plural': 'Tuman/Shaharlar',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='employees.district', verbose_name='Tumani'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='employees.region', verbose_name='Viloyati'),
        ),
    ]
